### ISSUE TITLE
面经-CSS

### ISSUE THREAD

**Issue by Jackie1210** [Jackie1210/vue_learning#6]
## 重绘和重排
浏览器下载完html，js等之后会形成DOM树和渲染树(每个节点以盒模型呈现)。

重排就是指当页面元素的宽高等发生变化时，需要重新生成渲染树。
- 添加或者删除可见的DOM元素
- 元素位置改变
- 元素尺寸改变
- 元素内容改变（例如：一个文本被另一个不同尺寸的图片替代）
- 页面渲染初始化（这个无法避免）
- 浏览器窗口尺寸改变

重绘就是只当元素的颜色等变化时进行的操作。

### 减少重排的方法
- DOM 的多个读操作（或多个写操作），应该放在一起
- 使用class
- 先将元素设为display: none（需要1次重排和重绘），然后对这个节点进行100次操作，最后再恢复显示（需要1次重排和重绘）。
- position属性为absolute或fixed的元素，使元素脱离文档流
## 脱离文档流的方法
float：并没有完全脱离，其余盒子内的文本还是看得见float的元素的

absolute:完全脱离文档流,邻近的元素会被覆盖

## 性能优化
html：css和js的位置
js：压缩代码（minify）、懒加载、合并脚本，使用cdn(内容分发网络)
DOM：事件委托、减少重排、分离读写操作
css：雪碧图
服务器：开启gzip，开启keepalive（减少连接次数），开启HTTP/2，减少重定向
客户端：使用本地缓存

### DOM0级事件模型
又称为原始事件模型，在该模型中，事件不会传播，即没有事件流的概念
```html
<input type="button" onclick="fun()">
```
### DOM2级事件模型
事件捕获=>事件处理=>事件冒泡
```javascript
var btn = document.getElementById('.btn');
btn.addEventListener(‘click’, showMessage, false);
//false表示在冒泡事件阶段响应事件
btn.removeEventListener(‘click’, showMessage, false);
```

## CSS布局
垂直居中的方法：
- flexbox;
- 绝对定位+margin（已知宽高）
``` css
  .element {
    width: 600px; height: 400px;
    position: absolute; left: 50%; top: 50%;
    margin-top: -200px;    /* 高度的一半 */
    margin-left: -300px;    /* 宽度的一半 */
}
```
- 绝对定位+transform（未知宽高）
```css
  .element {
    width: 600px; height: 400px;
    position: absolute; left: 50%; top: 50%;
    transform: translate(-50%, -50%);    /* 50%为自身尺寸的一半 */
}
```
- margin:auto
``` css
  .element {
    width: 600px; height: 400px;
    position: absolute; left: 0; top: 0; right: 0; bottom: 0;
    margin: auto;    /* 有了这个就自动居中了 */
}
```

## 盒子模型
border-box：content-box/border-box

## css布局（圣杯布局+双飞翼布局）
- 绝对定位+margin
- 圣杯布局
``` css
  <div id="bd">         
    <div class="main"></div>
    <div class="sub"></div>        
    <div class="extra"></div>  
</div>
.main {        
    float: left;       
    width: 100%;   
 }  
 .sub {       
    float: left;        
    width: 190px;        
    margin-left: -100%;               
    position: relative;  
    left: -190px;  
}   
.extra {        
    float: left;        
    width: 230px;        
    margin-left: -230px; 
    position: relative; 
    right: -230px;  
 }
#bd {        
    padding: 0 230px 0 190px;   
 }
```
- 双飞翼布局
```css
  <div class="main-wrap">
      <div class="main">#main</div>
  </div>
  <div class="sub"></div>        
  <div class="extra"></div>
  .main-wrap{
    width:100%;
    float:left;
  }
  .sub{
    float:left;
    width:190px;
    margin-left:-100%;
  }
  .extra{
    float:left;
    width:230px;
    margin-left:-230px;
  }
  .main{
    margin:0 230px 0 190px;
  }
```
## display(inline,inline-block,block)
- inline不能设置宽高，只有水平方向有padding，margin，垂直方向取决于line-height。
- block不能设置vertical-align
- inline-block可以设置vertical-align

## flexbox及其适用场景
垂直居中，几栏布局，兼容性差

## 流式布局，自适应布局，响应式布局
- 流式布局：使用max-width，min-width；使用百分比进行布局，无法进行像素级别的修改。
- 自适应布局：自适应布局的特点是分别为不同的屏幕分辨率定义布局，即创建**多个**静态布局，每个静态布局对应一个屏幕分辨率范围。不会改变样式与布局。
- 响应式布局：流式布局+自适应布局（随着页面的变化，页面的元素的样式会发生对应的变化），即一个页面可以在不同设备上运行。@media；同时当页面变化时，样式与布局都有可能发生变化。

## attribute和property
- 简单理解，Attribute就是dom节点自带的属性，例如html中常用的id、class、title、align等。

可以使用setAttribute（只能赋字符串）和getAttribute方法。修改的样式会立即返回到html上。

- Property是这个DOM元素作为对象，其附加的内容，例如childNodes、firstChild等。
property只要使用‘.’就可以进行操作了，赋值的话可以赋予任何形式的值。

数据的绑定是单项向的，attribute->property

## 移动端开发
响应式设计、Zepto；@media、viewport、JavaScript 正则表达式判断平台。

## bfc
- 块级格式化上下文:具有 BFC 特性的元素可以看作是隔离了的独立容器，容器里面的元素不会在布局上影响到外面的元素，并且 BFC 具有普通容器所没有的一些特性。
- 触发
  - body
  - 浮动元素
  - display：inline-block、flex
  - position:absolute,fixed
  - overflow:除visiable之外所有，常见的有hidden，auto
- 同一个 BFC 下竖直方向上外边距会发生折叠，以大的为准（使用overflow：hidden）
- BFC 可以包含浮动的元素（清除浮动）
- BFC 可以阻止元素被浮动元素覆盖
- 解决高度塌陷问题，因为float后脱离了文档流

## CSS选择器优先级
'#' > 伪类 = 类选择器 = 属性选择器 > 伪元素 = 标签（p,h1） 
## css加载是异步的
```html
  <head>
    <link rel="stylesheet" href="./index1.css">
    <link rel="stylesheet" href="./index2.css">
  </head>
```
- 谁先加载完先解析谁
- 若有相同的类，则index2.css覆盖index1.css

## 浏览器兼容性问题
- css问题（IE6/IE7）
```html 
<!--[if IE 6]>只有IE6可见<!endif>
```
- css
  - 链接的点击（love&hate）
  - 双边距问题：display：block
  - IE6没有min-width的概念
  - IE6下水平居中：margin：0 auto，父容器：text-align:center
  - IE6无法设置1px行高：overflow：hidden
- js兼容性
  - addEventListener&attachEvent
  - IE的事件捕获是从内到外
  - IE获取目标元素的方式不一样：event.srcElement&event.target
  - ajax:xmlHttpRequest&activeXObject
  - parentNode/childNodes&parentElement/children
*{margin:0;padding:0},reset.css,使用Autoprefixer

## 继承属性与非继承属性
- 非继承属性
1、display：规定元素应该生成的框的类型

2、文本属性：

vertical-align：垂直文本对齐

text-decoration：规定添加到文本的装饰

text-shadow：文本阴影效果

white-space：空白符的处理

unicode-bidi：设置文本的方向

3、盒子模型的属性：width、height、margin 、margin-top、margin-right、margin-bottom、margin-left、border、border-style、border-top-style、border-right-style、border-bottom-style、border-left-style、border-width、border-top-width、border-right-right、border-bottom-width、border-left-width、border-color、border-top-color、border-right-color、border-bottom-color、border-left-color、border-top、border-right、border-bottom、border-left、padding、padding-top、padding-right、padding-bottom、padding-left

4、背景属性：background、background-color、background-image、background-repeat、background-position、background-attachment

5、定位属性：float、clear、position、top、right、bottom、left、min-width、min-height、max-width、max-height、overflow、clip、z-index

6、生成内容属性：content、counter-reset、counter-increment

7、轮廓样式属性：outline-style、outline-width、outline-color、outline

8、页面样式属性：size、page-break-before、page-break-after

9、声音样式属性：pause-before、pause-after、pause、cue-before、cue-after、cue、play-during
- 继承属性
1、字体系列属性

font：组合字体

font-family：规定元素的字体系列

font-weight：设置字体的粗细

font-size：设置字体的尺寸

font-style：定义字体的风格

font-variant：设置小型大写字母的字体显示文本，这意味着所有的小写字母均会被转换为大写，但是所有使用小型大写字体的字母与其余文本相比，其字体尺寸更小。

font-stretch：对当前的 font-family 进行伸缩变形。所有主流浏览器都不支持。

font-size-adjust：为某个元素规定一个 aspect 值，这样就可以保持首选字体的 x-height。

2、文本系列属性

text-indent：文本缩进

text-align：文本水平对齐

line-height：行高

word-spacing：增加或减少单词间的空白（即字间隔）

letter-spacing：增加或减少字符间的空白（字符间距）

text-transform：控制文本大小写

direction：规定文本的书写方向

color：文本颜色

3、元素可见性：visibility

4、表格布局属性：caption-side、border-collapse、border-spacing、empty-cells、table-layout

5、列表布局属性：list-style-type、list-style-image、list-style-position、list-style

6、生成内容属性：quotes

7、光标属性：cursor

8、页面样式属性：page、page-break-inside、windows、orphans

9、声音样式属性：speak、speak-punctuation、speak-numeral、speak-header、speech-rate、volume、voice-family、pitch、pitch-range、stress、richness、、azimuth、elevation
